/**
 * Digital Receipts Compliance E2E Tests
 *
 * Verifies that the `confirm_order_delivery` RPC generates digital receipts
 * with the correct Florida cottage food footer text.
 *
 * This test operates at the API/DB level since digital receipts are not yet
 * displayed in the app UI — they are generated by the RPC and stored in the
 * `digital_receipts` table.
 *
 * Prerequisites:
 * - Local Supabase running with seed data
 * - receipt_footers table seeded with FL entry
 */

import { expect, test } from "@playwright/test";

const SUPABASE_URL = process.env.SUPABASE_URL || "http://127.0.0.1:54321";
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY ||
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU";

const SELLER_ID = "a1111111-1111-1111-1111-111111111111";
const BUYER_ID = "b2222222-2222-2222-2222-222222222222";

const FL_FOOTER =
    "MADE IN A COTTAGE FOOD OPERATION THAT IS NOT SUBJECT TO FLORIDA'S FOOD SAFETY REGULATIONS.";

async function supabaseRpc(fn: string, body: Record<string, unknown>) {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/rpc/${fn}`, {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            apikey: SUPABASE_SERVICE_KEY,
            Authorization: `Bearer ${SUPABASE_SERVICE_KEY}`,
        },
        body: JSON.stringify(body),
    });
    return res.json();
}

async function supabaseQuery(table: string, query: string) {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/${table}?${query}`, {
        headers: {
            apikey: SUPABASE_SERVICE_KEY,
            Authorization: `Bearer ${SUPABASE_SERVICE_KEY}`,
        },
    });
    return res.json();
}

async function supabasePatch(
    table: string,
    query: string,
    body: Record<string, unknown>,
) {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/${table}?${query}`, {
        method: "PATCH",
        headers: {
            "Content-Type": "application/json",
            apikey: SUPABASE_SERVICE_KEY,
            Authorization: `Bearer ${SUPABASE_SERVICE_KEY}`,
            Prefer: "return=minimal",
        },
        body: JSON.stringify(body),
    });
    return res;
}

async function supabaseDelete(table: string, query: string) {
    await fetch(`${SUPABASE_URL}/rest/v1/${table}?${query}`, {
        method: "DELETE",
        headers: {
            apikey: SUPABASE_SERVICE_KEY,
            Authorization: `Bearer ${SUPABASE_SERVICE_KEY}`,
            Prefer: "return=minimal",
        },
    });
}

test.describe.serial("Digital Receipts — Florida Compliance", () => {
    // These tests mutate shared DB state (community table) so they must only
    // run in one project. Skip the buyer project duplicate.
    test.beforeEach(async ({}, testInfo) => {
        if (testInfo.project.name === "buyer") {
            test.skip(true, "DB-mutating tests run only in seller project");
        }
    });

    // Track IDs of resources created during tests for cleanup
    const createdOrderIds: string[] = [];
    const createdConversationIds: string[] = [];

    // Clean up ALL test data after suite completes to avoid contaminating
    // other tests (offers, orders) that depend on seed data counts.
    test.afterAll(async () => {
        // Delete in FK-safe order: receipts → ledger → messages → orders → offers → conversations
        for (const orderId of createdOrderIds) {
            await supabaseDelete("digital_receipts", `order_id=eq.${orderId}`);
            await supabaseDelete("orders", `id=eq.${orderId}`);
        }
        for (const convId of createdConversationIds) {
            await supabaseDelete(
                "chat_messages",
                `conversation_id=eq.${convId}`,
            );
            await supabaseDelete("offers", `conversation_id=eq.${convId}`);
            await supabaseDelete("conversations", `id=eq.${convId}`);
        }
        // Restore community state
        await supabasePatch("communities", "h3_index=eq.89283470c2fffff", {
            state: "California",
        });
    });

    test("receipt_footers table contains required FL entry", async () => {
        const footers = await supabaseQuery(
            "receipt_footers",
            "state_code=eq.FL",
        );

        expect(footers.length).toBe(1);
        expect(footers[0].footer_text).toBe(FL_FOOTER);
        expect(footers[0].font_size_pt).toBe(10);
    });

    test("confirm_order_delivery generates receipt WITHOUT footer for non-FL states", async () => {
        // Ensure community is in California (not FL) before this test
        await supabasePatch("communities", "h3_index=eq.89283470c2fffff", {
            state: "California",
        });

        // 1. Create a test order
        const createResult = await supabaseRpc("create_order_atomic", {
            p_buyer_id: BUYER_ID,
            p_seller_id: SELLER_ID,
            p_post_id: "c3333333-3333-3333-3333-333333333333",
            p_quantity: 1,
            p_points_per_unit: 5,
            p_total_price: 5,
            p_category: "vegetables",
            p_product: "No Footer Tomatoes",
        });

        // Log error if RPC fails
        if (!createResult.orderId) {
            console.error(
                "create_order_atomic failed:",
                JSON.stringify(createResult),
            );
        }
        expect(createResult.orderId).toBeTruthy();

        const orderId = createResult.orderId;
        createdOrderIds.push(orderId);
        createdConversationIds.push(createResult.conversationId);

        // 2. Move to delivered
        await supabasePatch("orders", `id=eq.${orderId}`, {
            status: "accepted",
        });
        await supabasePatch("orders", `id=eq.${orderId}`, {
            status: "delivered",
        });

        // 3. Confirm delivery
        const confirmResult = await supabaseRpc("confirm_order_delivery", {
            p_order_id: orderId,
            p_buyer_id: BUYER_ID,
        });

        expect(confirmResult.success).toBe(true);

        // 4. Check receipt — footer should be null for California
        const receipts = await supabaseQuery(
            "digital_receipts",
            `order_id=eq.${orderId}&select=buyer_receipt,seller_receipt`,
        );

        expect(receipts.length).toBe(1);
        expect(receipts[0].buyer_receipt.footer).toBeNull();
        expect(receipts[0].seller_receipt.footer).toBeNull();
    });

    test("confirm_order_delivery generates receipt with FL cottage food footer", async () => {
        // 1. Set the seller's community state to "FL" so the footer applies
        await supabasePatch("communities", "h3_index=eq.89283470c2fffff", {
            state: "FL",
        });

        try {
            // 2. Create a test order via the RPC
            const createResult = await supabaseRpc("create_order_atomic", {
                p_buyer_id: BUYER_ID,
                p_seller_id: SELLER_ID,
                p_post_id: "c3333333-3333-3333-3333-333333333333",
                p_quantity: 1,
                p_points_per_unit: 10,
                p_total_price: 10,
                p_category: "vegetables",
                p_product: "Receipt Test Tomatoes",
            });

            if (!createResult.orderId) {
                console.error(
                    "create_order_atomic failed:",
                    JSON.stringify(createResult),
                );
            }
            expect(createResult.orderId).toBeTruthy();

            const orderId = createResult.orderId;
            createdOrderIds.push(orderId);
            createdConversationIds.push(createResult.conversationId);

            // 3. Move order through lifecycle
            await supabasePatch("orders", `id=eq.${orderId}`, {
                status: "accepted",
            });
            await supabasePatch("orders", `id=eq.${orderId}`, {
                status: "delivered",
            });

            // 4. Confirm delivery — this generates the digital receipt
            const confirmResult = await supabaseRpc("confirm_order_delivery", {
                p_order_id: orderId,
                p_buyer_id: BUYER_ID,
                p_harvest_date: "2026-03-01",
            });

            expect(confirmResult.success).toBe(true);

            // 5. Check the digital receipt in the DB
            const receipts = await supabaseQuery(
                "digital_receipts",
                `order_id=eq.${orderId}&select=buyer_receipt,seller_receipt`,
            );

            expect(receipts.length).toBe(1);

            const buyerReceipt = receipts[0].buyer_receipt;
            const sellerReceipt = receipts[0].seller_receipt;

            // Both receipts should contain the FL cottage food footer
            expect(buyerReceipt.footer).toBe(FL_FOOTER);
            expect(sellerReceipt.footer).toBe(FL_FOOTER);

            // Verify other receipt fields
            expect(buyerReceipt.product).toBe("Receipt Test Tomatoes");
            expect(buyerReceipt.quantity).toBe(1);
            expect(buyerReceipt.harvest_date).toBe("2026-03-01");
            expect(buyerReceipt.type).toBe("Affiliated Network Fulfillment");

            // Seller receipt should include platform fee info
            expect(sellerReceipt.platform_fee).toBeGreaterThanOrEqual(0);
            expect(sellerReceipt.fee_rate).toBeDefined();
        } finally {
            // 6. Restore community state to California
            await supabasePatch("communities", "h3_index=eq.89283470c2fffff", {
                state: "California",
            });
        }
    });
});
