/**
 * Produce Emoji Lookup
 * Maps common produce names to their emoji icons.
 * Used for auto-assigning emojis to custom garden items.
 */

const PRODUCE_EMOJI_MAP: Record<string, string> = {
    // ── Fruits ──
    "apple": "🍎",
    "apples": "🍎",
    "avocado": "🥑",
    "avocados": "🥑",
    "banana": "🍌",
    "bananas": "🍌",
    "blackberry": "🫐",
    "blackberries": "🫐",
    "blueberry": "🫐",
    "blueberries": "🫐",
    "cantaloupe": "🍈",
    "cherry": "🍒",
    "cherries": "🍒",
    "coconut": "🥥",
    "coconuts": "🥥",
    "cranberry": "🫐",
    "cranberries": "🫐",
    "date": "🌴",
    "dates": "🌴",
    "dragon fruit": "🐉",
    "dragonfruit": "🐉",
    "fig": "🫒",
    "figs": "🫒",
    "grape": "🍇",
    "grapes": "🍇",
    "grapefruit": "🍊",
    "guava": "🍈",
    "honeydew": "🍈",
    "kiwi": "🥝",
    "kiwis": "🥝",
    "kumquat": "🍊",
    "kumquats": "🍊",
    "lemon": "🍋",
    "lemons": "🍋",
    "lime": "🍋‍🟩",
    "limes": "🍋‍🟩",
    "lychee": "🍈",
    "lychees": "🍈",
    "mango": "🥭",
    "mangoes": "🥭",
    "mangos": "🥭",
    "melon": "🍈",
    "melons": "🍈",
    "nectarine": "🍑",
    "nectarines": "🍑",
    "olive": "🫒",
    "olives": "🫒",
    "orange": "🍊",
    "oranges": "🍊",
    "papaya": "🍈",
    "papayas": "🍈",
    "passion fruit": "🍈",
    "peach": "🍑",
    "peaches": "🍑",
    "pear": "🍐",
    "pears": "🍐",
    "persimmon": "🍊",
    "persimmons": "🍊",
    "pineapple": "🍍",
    "pineapples": "🍍",
    "plum": "🫐",
    "plums": "🫐",
    "pomegranate": "🍎",
    "pomegranates": "🍎",
    "raspberry": "🫐",
    "raspberries": "🫐",
    "rhubarb": "🌿",
    "starfruit": "⭐",
    "strawberry": "🍓",
    "strawberries": "🍓",
    "tangerine": "🍊",
    "tangerines": "🍊",
    "tomato": "🍅",
    "tomatoes": "🍅",
    "watermelon": "🍉",
    "watermelons": "🍉",

    // ── Vegetables ──
    "artichoke": "🌿",
    "artichokes": "🌿",
    "arugula": "🥬",
    "asparagus": "🌿",
    "beet": "🟣",
    "beets": "🟣",
    "bell pepper": "🫑",
    "bell peppers": "🫑",
    "bok choy": "🥬",
    "broccoli": "🥦",
    "brussels sprout": "🥬",
    "brussels sprouts": "🥬",
    "cabbage": "🥬",
    "carrot": "🥕",
    "carrots": "🥕",
    "cauliflower": "🥦",
    "celery": "🌿",
    "collard greens": "🥬",
    "collards": "🥬",
    "corn": "🌽",
    "cucumber": "🥒",
    "cucumbers": "🥒",
    "edamame": "🫛",
    "eggplant": "🍆",
    "endive": "🥬",
    "garlic": "🧄",
    "green bean": "🫘",
    "green beans": "🫘",
    "green onion": "🧅",
    "green onions": "🧅",
    "scallion": "🧅",
    "scallions": "🧅",
    "jalapeno": "🌶️",
    "jalapeño": "🌶️",
    "jalapenos": "🌶️",
    "kale": "🥬",
    "leek": "🧅",
    "leeks": "🧅",
    "lettuce": "🥬",
    "mushroom": "🍄",
    "mushrooms": "🍄",
    "okra": "🌿",
    "onion": "🧅",
    "onions": "🧅",
    "pea": "🫛",
    "peas": "🫛",
    "pepper": "🫑",
    "peppers": "🫑",
    "potato": "🥔",
    "potatoes": "🥔",
    "pumpkin": "🎃",
    "pumpkins": "🎃",
    "radish": "🥕",
    "radishes": "🥕",
    "snap pea": "🫛",
    "snap peas": "🫛",
    "sugar snap peas": "🫛",
    "spinach": "🥬",
    "squash": "🎃",
    "sweet potato": "🍠",
    "sweet potatoes": "🍠",
    "yam": "🍠",
    "yams": "🍠",
    "swiss chard": "🥬",
    "chard": "🥬",
    "taro": "🟤",
    "turnip": "🥕",
    "turnips": "🥕",
    "zucchini": "🥒",

    // ── Herbs ──
    "basil": "🌿",
    "bay leaf": "🌿",
    "bay leaves": "🌿",
    "chive": "🌿",
    "chives": "🌿",
    "cilantro": "🌿",
    "coriander": "🌿",
    "dill": "🌿",
    "fennel": "🌿",
    "ginger": "🫚",
    "lemongrass": "🌿",
    "marjoram": "🌿",
    "mint": "🌿",
    "oregano": "🌿",
    "parsley": "🌿",
    "rosemary": "🌿",
    "sage": "🌿",
    "tarragon": "🌿",
    "thai basil": "🌿",
    "thyme": "🌿",
    "turmeric": "🟡",

    // ── Flowers ──
    "anthurium": "❤️",
    "bird of paradise": "🌺",
    "black-eyed susan": "🌻",
    "black-eyed susans": "🌻",
    "bougainvillea": "🌺",
    "carnation": "🌸",
    "carnations": "🌸",
    "chrysanthemum": "🌼",
    "chrysanthemums": "🌼",
    "mum": "🌼",
    "mums": "🌼",
    "daffodil": "🌼",
    "daffodils": "🌼",
    "dahlia": "🌺",
    "dahlias": "🌺",
    "daisy": "🌼",
    "daisies": "🌼",
    "gardenia": "🤍",
    "gardenias": "🤍",
    "geranium": "🌺",
    "geraniums": "🌺",
    "hibiscus": "🌺",
    "hydrangea": "💙",
    "hydrangeas": "💙",
    "iris": "💜",
    "irises": "💜",
    "jasmine": "🌸",
    "lavender": "💜",
    "lily": "🌷",
    "lilies": "🌷",
    "marigold": "🌼",
    "marigolds": "🌼",
    "orchid": "🌷",
    "orchids": "🌷",
    "pansy": "🌸",
    "pansies": "🌸",
    "peony": "🌸",
    "peonies": "🌸",
    "petunia": "🌺",
    "petunias": "🌺",
    "plumeria": "🌸",
    "rose": "🌹",
    "roses": "🌹",
    "snapdragon": "🌸",
    "snapdragons": "🌸",
    "sunflower": "🌻",
    "sunflowers": "🌻",
    "tulip": "🌷",
    "tulips": "🌷",
    "violet": "💜",
    "violets": "💜",
    "zinnia": "🌺",
    "zinnias": "🌺",
};

/**
 * Looks up the emoji for a produce/plant name.
 * Case-insensitive matching, returns empty string if not found.
 */
export function getProduceEmoji(name: string): string {
    return PRODUCE_EMOJI_MAP[name.toLowerCase().trim()] || "";
}
