-- Seed all 50 US states, DC, and territories
INSERT INTO public.states (country_iso_3, code, name) VALUES
  ('USA', 'AL', 'Alabama'),
  ('USA', 'AK', 'Alaska'),
  ('USA', 'AZ', 'Arizona'),
  ('USA', 'AR', 'Arkansas'),
  -- CA already seeded with deterministic UUID in seed.sql
  ('USA', 'CO', 'Colorado'),
  ('USA', 'CT', 'Connecticut'),
  ('USA', 'DE', 'Delaware'),
  ('USA', 'FL', 'Florida'),
  ('USA', 'GA', 'Georgia'),
  ('USA', 'HI', 'Hawaii'),
  ('USA', 'ID', 'Idaho'),
  ('USA', 'IL', 'Illinois'),
  ('USA', 'IN', 'Indiana'),
  ('USA', 'IA', 'Iowa'),
  ('USA', 'KS', 'Kansas'),
  ('USA', 'KY', 'Kentucky'),
  ('USA', 'LA', 'Louisiana'),
  ('USA', 'ME', 'Maine'),
  ('USA', 'MD', 'Maryland'),
  ('USA', 'MA', 'Massachusetts'),
  ('USA', 'MI', 'Michigan'),
  ('USA', 'MN', 'Minnesota'),
  ('USA', 'MS', 'Mississippi'),
  ('USA', 'MO', 'Missouri'),
  ('USA', 'MT', 'Montana'),
  ('USA', 'NE', 'Nebraska'),
  ('USA', 'NV', 'Nevada'),
  ('USA', 'NH', 'New Hampshire'),
  ('USA', 'NJ', 'New Jersey'),
  ('USA', 'NM', 'New Mexico'),
  ('USA', 'NY', 'New York'),
  ('USA', 'NC', 'North Carolina'),
  ('USA', 'ND', 'North Dakota'),
  ('USA', 'OH', 'Ohio'),
  ('USA', 'OK', 'Oklahoma'),
  ('USA', 'OR', 'Oregon'),
  ('USA', 'PA', 'Pennsylvania'),
  ('USA', 'RI', 'Rhode Island'),
  ('USA', 'SC', 'South Carolina'),
  ('USA', 'SD', 'South Dakota'),
  ('USA', 'TN', 'Tennessee'),
  ('USA', 'TX', 'Texas'),
  ('USA', 'UT', 'Utah'),
  ('USA', 'VT', 'Vermont'),
  ('USA', 'VA', 'Virginia'),
  ('USA', 'WA', 'Washington'),
  ('USA', 'WV', 'West Virginia'),
  ('USA', 'WI', 'Wisconsin'),
  ('USA', 'WY', 'Wyoming'),
  -- District of Columbia
  ('USA', 'DC', 'District of Columbia'),
  -- US Territories
  ('USA', 'AS', 'American Samoa'),
  ('USA', 'GU', 'Guam'),
  ('USA', 'MP', 'Northern Mariana Islands'),
  ('USA', 'PR', 'Puerto Rico'),
  ('USA', 'VI', 'US Virgin Islands')
ON CONFLICT (country_iso_3, code) DO NOTHING;
