-- ============================================================================
-- Seed: Block cashout redemption in all US states
-- Cashout is not offered at this time.
-- ============================================================================

INSERT INTO state_redemption_method_blocks (state_code, method, reason) VALUES
  ('AL', 'cashout', 'Cash redemption is not currently available'),
  ('AK', 'cashout', 'Cash redemption is not currently available'),
  ('AZ', 'cashout', 'Cash redemption is not currently available'),
  ('AR', 'cashout', 'Cash redemption is not currently available'),
  ('CA', 'cashout', 'Cash redemption is not currently available'),
  ('CO', 'cashout', 'Cash redemption is not currently available'),
  ('CT', 'cashout', 'Cash redemption is not currently available'),
  ('DE', 'cashout', 'Cash redemption is not currently available'),
  ('FL', 'cashout', 'Cash redemption is not currently available'),
  ('GA', 'cashout', 'Cash redemption is not currently available'),
  ('HI', 'cashout', 'Cash redemption is not currently available'),
  ('ID', 'cashout', 'Cash redemption is not currently available'),
  ('IL', 'cashout', 'Cash redemption is not currently available'),
  ('IN', 'cashout', 'Cash redemption is not currently available'),
  ('IA', 'cashout', 'Cash redemption is not currently available'),
  ('KS', 'cashout', 'Cash redemption is not currently available'),
  ('KY', 'cashout', 'Cash redemption is not currently available'),
  ('LA', 'cashout', 'Cash redemption is not currently available'),
  ('ME', 'cashout', 'Cash redemption is not currently available'),
  ('MD', 'cashout', 'Cash redemption is not currently available'),
  ('MA', 'cashout', 'Cash redemption is not currently available'),
  ('MI', 'cashout', 'Cash redemption is not currently available'),
  ('MN', 'cashout', 'Cash redemption is not currently available'),
  ('MS', 'cashout', 'Cash redemption is not currently available'),
  ('MO', 'cashout', 'Cash redemption is not currently available'),
  ('MT', 'cashout', 'Cash redemption is not currently available'),
  ('NE', 'cashout', 'Cash redemption is not currently available'),
  ('NV', 'cashout', 'Cash redemption is not currently available'),
  ('NH', 'cashout', 'Cash redemption is not currently available'),
  ('NJ', 'cashout', 'Cash redemption is not currently available'),
  ('NM', 'cashout', 'Cash redemption is not currently available'),
  ('NY', 'cashout', 'Cash redemption is not currently available'),
  ('NC', 'cashout', 'Cash redemption is not currently available'),
  ('ND', 'cashout', 'Cash redemption is not currently available'),
  ('OH', 'cashout', 'Cash redemption is not currently available'),
  ('OK', 'cashout', 'Cash redemption is not currently available'),
  ('OR', 'cashout', 'Cash redemption is not currently available'),
  ('PA', 'cashout', 'Cash redemption is not currently available'),
  ('RI', 'cashout', 'Cash redemption is not currently available'),
  ('SC', 'cashout', 'Cash redemption is not currently available'),
  ('SD', 'cashout', 'Cash redemption is not currently available'),
  ('TN', 'cashout', 'Cash redemption is not currently available'),
  ('TX', 'cashout', 'Cash redemption is not currently available'),
  ('UT', 'cashout', 'Cash redemption is not currently available'),
  ('VT', 'cashout', 'Cash redemption is not currently available'),
  ('VA', 'cashout', 'Cash redemption is not currently available'),
  ('WA', 'cashout', 'Cash redemption is not currently available'),
  ('WV', 'cashout', 'Cash redemption is not currently available'),
  ('WI', 'cashout', 'Cash redemption is not currently available'),
  ('WY', 'cashout', 'Cash redemption is not currently available'),
  ('DC', 'cashout', 'Cash redemption is not currently available')
ON CONFLICT (country_iso_3, state_code, method) DO NOTHING;
