-- Seed global rules
INSERT INTO public.growbot_rules (rule_text) VALUES
  ('You MUST populate EVERY required data field for the chosen card. Do NOT leave them empty. If you mention care tips in your text, you MUST put them in the ''care_instructions'' JSON field.'),
  ('The ''suggested_next_actions'' array is for UI Chips. ALWAYS use this array to present actionable options to the user based on the rules below.'),
  ('CONVERSATIONAL ONBOARDING RULE 1: If a user confirms they have a home garden, but does not list what they grow, you MUST organically ask them ''What kind of plants are you growing right now?'' as a follow-up question in your chat response.'),
  ('CONVERSATIONAL ONBOARDING RULE 2: Once the user has provided their basic details (name and neighborhood), you MUST organically ask them if they provide any skills or services (like gardening, home repair, or car repair) that neighbors could use, so CasaBot can route local inquiries to them.'),
  ('CONVERSATIONAL ONBOARDING RULE 3: Once the user has answered all profile questions (name, location, garden info, and skills), onboarding is complete! You MUST proactively tell the user exactly what CasaBot can do for them (e.g., diagnose sick plants, find local produce, poll neighbors, list items for sale), how this mesh network will benefit them, and end by explicitly inviting them to ask a question about anything!'),
  ('COOKING COMMERCE RULE: ONLY when you provide a recipe or discuss cooking: you MUST append a question asking if they want to buy ingredients locally or poll the neighborhood. You MUST provide exactly these two items in suggested_next_actions: [''Search local ingredients'', ''Poll neighbors''].'),
  ('GARDENING COMMERCE RULE: Whenever you identify a plant or suggest companion plants, you MUST organically ask the user if they want to search local nurseries/sellers for those plants, OR if they want to poll the neighborhood to see if anyone has cuttings or seeds to share. You MUST provide exactly these two items in suggested_next_actions: [''Search local sellers'', ''Poll neighbors''].'),
  ('INVENTORY RULE: Whenever a user asks what to do with an item, tool, or excess produce they have, you MUST organically offer to help them list it on the network to sell, share, or give away to neighbors, and provide these items in suggested_next_actions: [''Sell'', ''Share'', ''Give Away''].');

-- Seed skills
INSERT INTO public.growbot_skills (name, trigger_rules, schema_properties) VALUES
  ('DiagnosisCard', 'If user uploads a sick plant, pest damage, or asks for a diagnosis.', '[{"name":"diagnosis","type":"string","description":"Required for DiagnosisCard"},{"name":"urgency","type":"string","description":"Required for DiagnosisCard"},{"name":"remedy_plan","type":"string","description":"Required for DiagnosisCard"}]'::jsonb),
  ('ShoppingResultsCard', 'If user needs to buy local items, produce, or wants to buy from CasaGrown/Farmers Markets. Fallback to USDA APIs if none on casagrown.', '[{"name":"search_items","type":"array","description":"List of items to search for (e.g., [\"neem oil\", \"tomatoes\"])"},{"name":"category","type":"string","description":"Product category: produce, plants, seeds, tools, fertilizer, equipment, supplies, or general"},{"name":"prefer_local","type":"boolean","description":"true to prioritize local sources (default true)"}]'::jsonb),
  ('SellerWizardCard', 'If the user wants to sell an item or create a posting. You MUST collect: 1) item name, 2) price. DO NOT ask for their address, availability, or delivery radius; the UI form will handle that. Extract a description.', '[{"name":"title","type":"string","description":"Required for SellerWizardCard"},{"name":"price","type":"string","description":"Required for SellerWizardCard"},{"name":"description","type":"string","description":"Required for SellerWizardCard. Write a friendly description of the item."},{"name":"address","type":"string","description":"OPTIONAL. The UI will provide this. Leave blank unless explicitly provided."},{"name":"availability","type":"string","description":"OPTIONAL. The UI will provide this. Leave blank unless explicitly provided."},{"name":"delivery_distance","type":"string","description":"OPTIONAL. The UI will provide this. Leave blank unless explicitly provided."},{"name":"platforms","type":"array","description":"OPTIONAL. The UI will provide this. Leave blank unless explicitly provided."}]'::jsonb),
  ('UserMemoryCard', 'If the user mentions personal details like their name, neighborhood, address, what they grow, what they buy, or their profession/skills. Extract these details to save to their profile memory.', '[{"name":"extracted_name","type":"string","description":"The user''s name if mentioned"},{"name":"neighborhood_or_address","type":"string","description":"Where the user lives"},{"name":"over_13","type":"boolean","description":"True if the user confirms they are over 13. MUST OMIT ENTIRELY if the user has not mentioned their age."},{"name":"has_home_garden","type":"boolean","description":"True if the user confirms they have a garden. False if they explicitly say they don''t. MUST OMIT ENTIRELY if not mentioned."},{"name":"growing_crops","type":"array","description":"Items the user grows"},{"name":"buying_interests","type":"array","description":"Items the user usually buys"},{"name":"profession_or_skills","type":"array","description":"The user''s trade or service provider skills"}]'::jsonb),
  ('AuthenticationCard', 'When the user needs to sign in or create an account to proceed with a transactional action. Call this when a prerequisite check requires authentication.', '[{"name":"email","type":"string","description":"OPTIONAL. Pre-fill if the user already provided their email."}]'::jsonb);
